version: '2'
services:
    auditlog-mongodb:
        container_name: auditlog-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/auditLog/mongodb/:/data/db/
